language: node_js
sudo: false
node_js:
  - 11

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test

before_deploy:
  - npm run release

deploy:
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token:
      secure:
    on:
      branch: master
